DROP SCHEMA IF EXISTS WORKSHOP_UNO;

CREATE SCHEMA IF NOT EXISTS WORKSHOP_UNO;

USE WORKSHOP_UNO;

CREATE TABLE IF NOT EXISTS CLIENTES (
IDCLIENTES INT AUTO_INCREMENT,
CEDULA INT,
NOMBRE VARCHAR(45) NOT NULL,
APELLIDO VARCHAR(45) NOT NULL,
TELEFONO VARCHAR(15),
FECHA_I_M_E DATE,
PRIMARY KEY(IDCLIENTES)
);

INSERT INTO CLIENTES (NOMBRE, APELLIDO)
VALUES ('IGNACIO', 'COLETTA');

CREATE TABLE IF NOT EXISTS FACTURA (
IDFACTURA INT AUTO_INCREMENT,
IVA DOUBLE,
SUBTOTAL DOUBLE,
IDCLIENTES INT ,
PRIMARY KEY(IDFACTURA)
);


INSERT INTO FACTURA (IVA, SUBTOTAL, IDCLIENTES)
VALUES (2, 100, 1);

ALTER TABLE FACTURA ADD FOREIGN KEY (IDCLIENTES) 
REFERENCES CLIENTES (IDCLIENTES);


CREATE TABLE IF NOT EXISTS DETALLE (
IDDETALLE INT AUTO_INCREMENT,
CANTIDAD DECIMAL,
TOTAL DOUBLE,
IDFACTURA INT ,
PRIMARY KEY (IDDETALLE),
FOREIGN KEY (IDFACTURA) REFERENCES FACTURA (IDFACTURA)
);

INSERT INTO DETALLE (CANTIDAD, IDFACTURA)
VALUES (30, 1);

SELECT * FROM CLIENTES;
SELECT * FROM FACTURA;
SELECT * FROM DETALLE;