
DROP FUNCTION IF EXISTS F_ES_BICIESTO;

DELIMITER $$
CREATE FUNCTION F_ES_BICIESTO(P_ANIO INT)
RETURNS BOOLEAN
DETERMINISTIC
BEGIN
    RETURN (P_ANIO % 4 = 0 AND P_ANIO % 100 != 0) OR (P_ANIO % 400 = 0);
END $$
DELIMITER ;

-- SELECT F_ES_BICIESTO(2025);

DROP FUNCTION IF EXISTS FN_VENTAS_DEL_MES;
DELIMITER $$

DROP FUNCTION IF EXISTS FN_VENTAS_DEL_MES;
DELIMITER $$
CREATE FUNCTION FN_VENTAS_DEL_MES(P_MES VARCHAR(2), P_ANIO VARCHAR(4))
RETURNS INT
DETERMINISTIC
BEGIN
    DECLARE V_FECHA_FIN_MES DATE;
    DECLARE V_FECHA_INICIO_MES DATE;
    DECLARE V_TOTAL_VENTAS INT;
    
    SET V_FECHA_INICIO_MES = STR_TO_DATE(CONCAT(P_ANIO, '-', P_MES, '-01'), '%Y-%m-%d'); 
    IF P_MES = 2 THEN
		IF F_ES_BICIESTO(P_ANIO) THEN 
			SET V_FECHA_FIN_MES = STR_TO_DATE(CONCAT(P_ANIO, '-', P_MES, '-29'), '%Y-%m-%d'); 
		ELSE
			SET V_FECHA_FIN_MES = STR_TO_DATE(CONCAT(P_ANIO, '-', P_MES, '-28'), '%Y-%m-%d');
		END IF;
    ELSE
		CASE 
			WHEN P_MES = '04' OR P_MES = '06' OR P_MES = '09' OR P_MES = '11' THEN
				SET V_FECHA_FIN_MES = STR_TO_DATE(CONCAT(P_ANIO, '-', P_MES, '-30'), '%Y-%m-%d');
			WHEN P_MES = '01' OR P_MES = '03' OR P_MES = '05' OR P_MES = '07' OR P_MES = '08' OR P_MES = '10' THEN
				SET V_FECHA_FIN_MES = STR_TO_DATE(CONCAT(P_ANIO, '-', P_MES, '-31'), '%Y-%m-%d');
			ELSE
				SET V_FECHA_FIN_MES = NULL;
		END CASE;
	END IF;
    
    SELECT COUNT(*)
    INTO V_TOTAL_VENTAS
    FROM FACTURA
    WHERE FACTURA.FECHA_FACTURA >= V_FECHA_INICIO_MES AND FACTURA.FECHA_FACTURA <= V_FECHA_FIN_MES;
    
    RETURN V_TOTAL_VENTAS;
END $$
DELIMITER ;
