DROP TRIGGER IF EXISTS TR_ACTUALIZAR_STOCK;

DELIMITER $$

CREATE TRIGGER TR_ACTUALIZAR_STOCK
AFTER INSERT ON DETALLE
FOR EACH ROW
BEGIN
	DECLARE CANTIDAD_PRODUCTO_DETALLE INT;
    DECLARE ID_PRODUCTO_DETALLE INT;
    
    SELECT NEW.CANTIDAD, NEW.ID_PRODUCTO 
    INTO CANTIDAD_PRODUCTO_DETALLE, ID_PRODUCTO_DETALLE;
    
	UPDATE PRODUCTO
    SET STOCK = STOCK - CANTIDAD_PRODUCTO
    WHERE ID_PRODUCTO = ID_PRODUCTO_DETALLE;
END; $$

DELIMITER ;

DROP TRIGGER IF EXISTS TR_VERIFICAR_STOCK_PRE_INSERCION;
DELIMITER $$

CREATE TRIGGER TR_VERIFICAR_STOCK_PRE_INSERCION
BEFORE INSERT ON DETALLE
FOR EACH ROW
BEGIN
	DECLARE STOCK_DISPONIBLE INT;
    
    SELECT STOCK 
    INTO STOCK_DISPONIBLE
    FROM PRODUCTO
    WHERE ID_PRODUCTO = NEW.ID_PRODUCTO;
    
    IF NEW.CANTIDAD > STOCK_DISPONIBLE THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'STOCK INSUFICIENTE';
    END IF;
END; $$

DELIMITER ;