SET AUTOCOMMIT = 0;
-- SELECT @@autocommit;

START TRANSACTION;

DELETE FROM CALIFICACION
WHERE CALIFICACION.ID_CALIFICACION >= 13;

-- SELECT * FROM CALIFICACION;
-- ROLLBACK;
COMMIT;


START TRANSACTION;

INSERT INTO CALIFICACION (ID_CLIENTE, ID_PRODUCTO, PUNTUACION, COMENTARIO) VALUES
 (1, 6, 6, 'SE BORRA LA IMAGEN, PERO QUEDA LISA Y EL AMARILLO ES DIVINO'), -- 13
 (7, 5, 6, 'BOB ESPONJA NI SE PARECE AL DE LA FOTO ORIGINAL'), -- 14
 (7, 10, 10, 'EXCELENTE CALIDAD, LE DOY UN 10/10'); -- 15

COMMIT; 

-- SELECT * FROM CALIFICACION;

START TRANSACTION;
-- SELECT * FROM TALLE;
INSERT INTO TALLE (MEDIDA) VALUES ('6XL'), ('7XL'),('8XL'),('9XL');
SAVEPOINT SP1;
INSERT INTO TALLE (MEDIDA) VALUES ('10XL'), ('11XL'),('12XL'),('13XL');
SAVEPOINT SP2;
ROLLBACK TO SP1;
-- ROLLBACK;
-- COMMIT;
-- SELECT * FROM TALLE;
